name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.weather-api-key }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nose2 flake8

      - name: Run tests
        run: nose2

      - name: Lint code
        run: flake8 . --count --max-line-length=100 --show-source --statistics

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/weather-app
